### ISSUE TITLE
how to always load (in init file)

### ISSUE THREAD

**Issue by mooseyboots** [mmontone/slime-star#1]
hi, thanks for this. the improved documentation is really helpful for me as a newcomer. i expect breakpoints will be too.

i wanted to ask how to always have this load with slime.

i have the two config lines from the readme in my init file, but slime-star functions don't load by default. i have to manually evaluate them for them to take effect. 

i use straight/use-package, and tried putting them before, inside and after my use-packge slime declaration. it can't go before, because slime contribs is undefined. is there perhaps an extra line needed if the code is inside or after?

or should it perhaps just work inside or after but i'm doing something else wrong?

**Comment by martianhi** [comment]
lol now that i finally got around to reporting this, i also worked it out:

```
  ;; slime-star:
  (add-to-list 'load-path "~/code/cl/slime-star")  
  (slime-setup '(slime-fancy slime-asdf slime-quicklisp slime-star))
```

works for me, adding slime-start to slime-contribs before or after slime-setup wouldn't work.
