### ISSUE TITLE
code navigation support for package local nicknames?

### ISSUE THREAD

**Issue by mooseyboots** [mmontone/slime-star#2]
did i understand the caption in the readme correctly that suggests slime-star supports this?

i'm looking for a way for `slime-edit-definition` and friends to work with package local nicknames.

**Comment by mmontone** [comment]
Mm no. I don't see package local nicknames being mentioned in the README, and this is not implemented.

Would be interesting to implement. Do you know if SLIME doesn't do it and why?

**Comment by martianhi** [comment]
thanks for your response.

i asked on the slime repo also., after first trying all slime's nav commands. https://github.com/slime/slime/issues/789.

i'm surprised it isn't obvious. maybe it's coz i'm a beginner, but i find i rely on both features heavily, the nav especially when getting to know a new library by trying it out... it has me wondering how the old hands handle it.

**Comment by mmontone** [comment]
Yes, local-package-nicknames don't work in SLIME for me either. I may try to implement depending on what they answer in that issue.

**Comment by mmontone** [comment]
I've patched Swank:

```lisp
(in-package :swank)

(defun eval-for-emacs (form buffer-package id)
  "Bind *BUFFER-PACKAGE* to BUFFER-PACKAGE and evaluate FORM.
Return the result to the continuation ID.
Errors are trapped and invoke our debugger."
  (let (ok result condition)
    (unwind-protect
         (let ((*buffer-package* (guess-buffer-package buffer-package))
               (*buffer-readtable* (guess-buffer-readtable buffer-package))
               (*pending-continuations* (cons id *pending-continuations*)))
           (check-type *buffer-package* package)
           (check-type *buffer-readtable* readtable)
           ;; APPLY would be cleaner than EVAL. 
           ;; (setq result (apply (car form) (cdr form)))
           (handler-bind ((t (lambda (c) (setf condition c))))
             (setq result (with-slime-interrupts
                            (let ((*package* (find-package *buffer-package*)))
                              (eval form)))))
           (run-hook *pre-reply-hook*)
           (setq ok t))
      (send-to-emacs `(:return ,(current-thread)
                               ,(if ok
                                    `(:ok ,result)
                                    `(:abort ,(prin1-to-string condition)))
                               ,id)))))
```

Load this code and see if it works for you. I think it is working for me.

**Comment by martianhi** [comment]
it works for me too, thanks.

i have since realized that getting docs also doesn't work with nicknames (maybe slime barely supports them?). perhaps it could be solved similarly?

**Comment by mmontone** [comment]
Docs work for me. Can you paste a backtrace of the error?
