### ISSUE TITLE
error in inline overlay

### ISSUE THREAD

**Issue by bo-tato** [mmontone/slime-star#3]
I've started using this recently, it's very nice. First minor bug I run into is if you have `(+ 1 2)` with the cursor on `+`, and do `slime-eval-defun`, it doesn't show result but gets `error in process filter: Scan error: "Containing expression ends prematurely", 1, 1` because an error is raised by `(backward-sexp 1)` in `inline-message`. I'm not sure the best way to solve it, maybe just wrapping it with `(ignore-errors (backward-sexp 1))`? then the result overlay shows fine and at the correct position

**Comment by mmontone** [comment]
I don't observe that problem. Like in the gif?

![Peek 2024-12-13 09-42](https://github.com/user-attachments/assets/ddb4ee44-08ce-4da3-b51f-3ac5cc460ac0)

**Comment by bo-tato** [comment]
I think in that gif your cursor is one to the right of what I mean:
![Peek 2024-12-13 15-58](https://github.com/user-attachments/assets/318d46eb-c4a5-4c4f-a2f3-a426280a6625)
